name: Reusable GitHub Packages Publisher

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
    secrets:
      USER_GITHUB_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.USER_GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle (fallback if no wrapper)
        uses: gradle/actions/setup-gradle@v3

      - name: Fetch repo
        id: version
        run: |
          git fetch origin
          git reset --hard origin/master

      - name: Calculate expected version
        id: version
        run: |
          tz="Asia/Bangkok"
          year=$(TZ=$tz date +"%Y")
          month=$(TZ=$tz date +"%-m")
          day=$(TZ=$tz date +"%-d")

          case "$month" in
            1)  m1=0; m2=1 ;;
            2)  m1=0; m2=2 ;;
            3)  m1=0; m2=3 ;;
            4)  m1=0; m2=4 ;;
            5)  m1=0; m2=5 ;;
            6)  m1=0; m2=6 ;;
            7)  m1=0; m2=7 ;;
            8)  m1=0; m2=8 ;;
            9)  m1=0; m2=9 ;;
            10) m1=1; m2=0 ;;
            11) m1=1; m2=1 ;;
            12) m1=1; m2=2 ;;
          esac

          if [ "$day" -eq 1 ]; then
            version="$year.$m1.$m2"
          else
            version="$year.$m1.$m2-$day"
          fi

          echo "Debug: year=$year, month=$month, day=$day, version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Make gradlew executable (if exists)
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          fi

      - name: Publish to GitHub Packages
        id: publish
        run: |
          if [ -f ./gradlew ] && [ -f ./gradle/wrapper/gradle-wrapper.jar ]; then
            ./gradlew publish
          else
            echo "Gradle wrapper not found. Falling back to system Gradle."
            gradle publish
          fi
        env:
          USER_GIT_NAME: ${{ github.actor }}
          USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          REPO_NAME: ${{ inputs.repo-name }}

      - name: Create GitHub Release
        if: success()
        run: |
          version="${{ steps.version.outputs.version }}"
          tag="$version"
          body="Automated release for version $version"

          git config user.name "agent-mcengine"
          git config user.email "agent-mcengine@users.noreply.github.com"
          git tag "$tag"
          git push origin "$tag"

          curl -s -X POST https://api.github.com/repos/${{ github.repository }}/releases \
            -H "Authorization: token ${{ secrets.USER_GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "tag_name": "$tag",
            "name": "$tag",
            "body": "$body",
            "draft": false,
            "prerelease": false
          }
          EOF
